// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eDreYSBqUCxfxxx8v4DS41
// Component: rKr9k50OBUmiSj
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { DataFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: ae7V86eNoXA/codeComponent
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: Vho_dnFwGMJ8/codeComponent
import TextInput from "../../TextInput"; // plasmic-import: QIeTN8-XMPAbP-/component
import Button from "../../Button"; // plasmic-import: sz19KgE1N3LEG/component

import { useScreenVariants as useScreenVariants_1VzYrrYr43S2Dd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 1VZYrrYR43S2dd/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_markup.module.css"; // plasmic-import: eDreYSBqUCxfxxx8v4DS41/projectcss
import sty from "./PlasmicSqueeze.module.css"; // plasmic-import: rKr9k50OBUmiSj/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: o-m1RL5SjlY6FZ/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: zj2sJSVI5_vwJ5/icon

export type PlasmicSqueeze__VariantMembers = {};
export type PlasmicSqueeze__VariantsArgs = {};
type VariantPropType = keyof PlasmicSqueeze__VariantsArgs;
export const PlasmicSqueeze__VariantProps = new Array<VariantPropType>();

export type PlasmicSqueeze__ArgsType = {};
type ArgPropType = keyof PlasmicSqueeze__ArgsType;
export const PlasmicSqueeze__ArgProps = new Array<ArgPropType>();

export type PlasmicSqueeze__OverridesType = {
  root?: p.Flex<"div">;
  httpApiFetcher?: p.Flex<typeof DataFetcher>;
  head?: p.Flex<typeof PlasmicHead>;
  form?: p.Flex<"form">;
};

export interface DefaultSqueezeProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSqueeze__RenderFunc(props: {
  variants: PlasmicSqueeze__VariantsArgs;
  args: PlasmicSqueeze__ArgsType;
  overrides: PlasmicSqueeze__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_1VzYrrYr43S2Dd()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicSqueeze.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicSqueeze.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicSqueeze.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
          id={(() => {
            try {
              return $ctx.params.slug;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        >
          <DataFetcher
            data-plasmic-name={"httpApiFetcher"}
            data-plasmic-override={overrides.httpApiFetcher}
            className={classNames("__wab_instance", sty.httpApiFetcher)}
            dataName={"fetchDyanamicData" as const}
            errorDisplay={
              <ph.DataCtxReader>
                {$ctx => "Error fetching data"}
              </ph.DataCtxReader>
            }
            headers={{
              "Content-Type": "application/json",
              Accept: "application/json",
              Authorization: "Bearer keyVDvhyVSx5Ntbl3"
            }}
            loadingDisplay={
              <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
            }
            method={"GET" as const}
            noLayout={false}
            url={(() => {
              try {
                return (
                  "https://api.airtable.com/v0/appmM1mMqcDvugXhY/PlasmicCMS/" +
                  $ctx.params.slug
                );
              } catch (e) {
                if (e instanceof TypeError) {
                  return "https://api.airtable.com/v0/appmM1mMqcDvugXhY/PlasmicCMS?slug";
                }
                throw e;
              }
            })()}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <React.Fragment>
                  <PlasmicHead
                    data-plasmic-name={"head"}
                    data-plasmic-override={overrides.head}
                    className={classNames("__wab_instance", sty.head)}
                    description={(() => {
                      try {
                        return $ctx.fetchDyanamicData.fields[
                          "Step 2 SEO Description"
                        ];
                      } catch (e) {
                        if (e instanceof TypeError) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    image={(() => {
                      try {
                        return undefined;
                      } catch (e) {
                        if (e instanceof TypeError) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    title={(() => {
                      try {
                        return $ctx.fetchDyanamicData.fields[
                          "Step 2 SEO Title"
                        ];
                      } catch (e) {
                        if (e instanceof TypeError) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kOy7O)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__oxMvR
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__nDtG5)}
                          displayHeight={"56px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={(() => {
                            try {
                              return $ctx.fetchDyanamicData.fields.logo[0].url;
                            } catch (e) {
                              if (e instanceof TypeError) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />
                      </div>

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns__moK19
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__geIkw
                            )}
                          >
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.columns__fcvqx
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column___4472Y
                                )}
                              >
                                <p.PlasmicImg
                                  alt={""}
                                  className={classNames(sty.img__xNf49)}
                                  displayHeight={"175px" as const}
                                  displayMaxHeight={"none" as const}
                                  displayMaxWidth={"100%" as const}
                                  displayMinHeight={"0" as const}
                                  displayMinWidth={"0" as const}
                                  displayWidth={
                                    hasVariant(
                                      globalVariants,
                                      "screen",
                                      "mobileOnly"
                                    )
                                      ? ("170px" as const)
                                      : ("196px" as const)
                                  }
                                  loading={"lazy" as const}
                                  src={(() => {
                                    try {
                                      return $ctx.fetchDyanamicData.fields
                                        .sThumbail[0].url;
                                    } catch (e) {
                                      if (e instanceof TypeError) {
                                        return undefined;
                                      }
                                      throw e;
                                    }
                                  })()}
                                />
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__lJ7Hv
                                )}
                              >
                                {(
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                ) ? (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__cTHmg
                                    )}
                                  >
                                    {(() => {
                                      try {
                                        return $ctx.fetchDyanamicData.fields
                                          .sH1;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "Enter some text";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </div>
                                ) : null}
                                {(
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                ) ? (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__xYwy
                                    )}
                                  >
                                    {(() => {
                                      try {
                                        return $ctx.fetchDyanamicData.fields
                                          .sH2;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "undefine";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </div>
                                ) : null}
                                {(
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                ) ? (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__fj2DY
                                    )}
                                  >
                                    {(() => {
                                      try {
                                        return $ctx.fetchDyanamicData.fields
                                          .sH1;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "Enter some text";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </div>
                                ) : null}
                                {(
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                ) ? (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__soMg
                                    )}
                                  >
                                    {(() => {
                                      try {
                                        return $ctx.fetchDyanamicData.fields
                                          .sH2;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "Enter some text";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </div>
                                ) : null}

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___6BuYh
                                  )}
                                >
                                  {(() => {
                                    try {
                                      return $ctx.fetchDyanamicData.fields.sH3;
                                    } catch (e) {
                                      if (e instanceof TypeError) {
                                        return "Enter some text";
                                      }
                                      throw e;
                                    }
                                  })()}
                                </div>
                              </div>
                            </p.Stack>
                          </div>
                        </div>
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__eGpt
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___7TqsT
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qe6Gw
                            )}
                          >
                            {(
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? true
                                : true
                            ) ? (
                              <button
                                className={classNames(
                                  projectcss.all,
                                  projectcss.button,
                                  projectcss.__wab_text,
                                  sty.button__nuCo
                                )}
                              >
                                {(() => {
                                  try {
                                    return $ctx.fetchDyanamicData.fields.sBadge;
                                  } catch (e) {
                                    if (e instanceof TypeError) {
                                      return "Click Me";
                                    }
                                    throw e;
                                  }
                                })()}
                              </button>
                            ) : null}
                          </div>
                        </div>
                      </div>

                      <form
                        data-plasmic-name={"form"}
                        data-plasmic-override={overrides.form}
                        action={
                          "https://hook.us1.make.com/5mordka6hk6nytd9doqnbe6kbf4r3drk" as const
                        }
                        className={classNames(projectcss.all, sty.form)}
                        method={"post" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__okxvU
                          )}
                        >
                          {(() => {
                            try {
                              return $ctx.fetchDyanamicData.fields.sH4;
                            } catch (e) {
                              if (e instanceof TypeError) {
                                return "Enter some text";
                              }
                              throw e;
                            }
                          })()}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eQxxl
                          )}
                        >
                          {(() => {
                            try {
                              return $ctx.fetchDyanamicData.fields.sH5;
                            } catch (e) {
                              if (e instanceof TypeError) {
                                return "Enter some text";
                              }
                              throw e;
                            }
                          })()}
                        </div>

                        <TextInput
                          aria-label={"email" as const}
                          className={classNames(
                            "__wab_instance",
                            sty.textInput__opAz9
                          )}
                          name={"email" as const}
                          placeholder={"📧 Your Email Address" as const}
                        />

                        <TextInput
                          aria-label={"phone" as const}
                          className={classNames(
                            "__wab_instance",
                            sty.textInput__eKwe
                          )}
                          name={"phone" as const}
                          placeholder={"📲 Your Phone Number" as const}
                        />

                        {true ? (
                          <TextInput
                            aria-label={"record_id" as const}
                            className={classNames(
                              "__wab_instance",
                              sty.textInput__qPjPo
                            )}
                            defaultValue={(() => {
                              try {
                                return $ctx.fetchDyanamicData.id;
                              } catch (e) {
                                if (e instanceof TypeError) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                            name={"record_id" as const}
                          />
                        ) : null}

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__qzzCx
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aXoyI
                            )}
                          >
                            {"Get Offer"}
                          </div>
                        </Button>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__clSa
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "I agree to receive emails and texts."
                            : "I agree to receive emails and texts."}
                        </div>
                      </form>

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__t4Z7
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__aoIym)}
                            displayHeight={"56px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"auto" as const}
                            loading={"lazy" as const}
                            src={(() => {
                              try {
                                return $ctx.fetchDyanamicData.fields.logo[0]
                                  .url;
                              } catch (e) {
                                if (e instanceof TypeError) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />
                        </div>
                      ) : null}
                    </div>
                  ) : null}
                </React.Fragment>
              )}
            </ph.DataCtxReader>
          </DataFetcher>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "httpApiFetcher", "head", "form"],
  httpApiFetcher: ["httpApiFetcher", "head", "form"],
  head: ["head"],
  form: ["form"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  httpApiFetcher: typeof DataFetcher;
  head: typeof PlasmicHead;
  form: "form";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSqueeze__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSqueeze__VariantsArgs;
    args?: PlasmicSqueeze__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSqueeze__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSqueeze__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSqueeze__ArgProps,
          internalVariantPropNames: PlasmicSqueeze__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSqueeze__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSqueeze";
  } else {
    func.displayName = `PlasmicSqueeze.${nodeName}`;
  }
  return func;
}

export const PlasmicSqueeze = Object.assign(
  // Top-level PlasmicSqueeze renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    httpApiFetcher: makeNodeComponent("httpApiFetcher"),
    head: makeNodeComponent("head"),
    form: makeNodeComponent("form"),

    // Metadata about props expected for PlasmicSqueeze
    internalVariantProps: PlasmicSqueeze__VariantProps,
    internalArgProps: PlasmicSqueeze__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Squeeze",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSqueeze;
/* prettier-ignore-end */
